INSERT INTO Genre (GenreId, Name) VALUES
    (1, 'Rock'),
    (2, 'Jazz'),
    (3, 'Metal'),
    (4, 'Alternative & Punk'),
    (5, 'Rock And Roll'),
    (6, 'Blues'),
    (7, 'Latin'),
    (8, 'Reggae'),
    (9, 'Pop'),
    (10, 'Soundtrack'),
    (11, 'Bossa Nova'),
    (12, 'Easy Listening'),
    (13, 'Heavy Metal'),
    (14, 'R&B/Soul'),
    (15, 'Electronica/Dance'),
    (16, 'World'),
    (17, 'Hip Hop/Rap'),
    (18, 'Science Fiction'),
    (19, 'TV Shows'),
    (20, 'Sci Fi & Fantasy'),
    (21, 'Drama'),
    (22, 'Comedy'),
    (23, 'Alternative'),
    (24, 'Classical'),
    (25, 'Opera');

INSERT INTO MediaType (MediaTypeId, Name) VALUES
    (1, 'MPEG audio file'),
    (2, 'Protected AAC audio file'),
    (3, 'Protected MPEG-4 video file'),
    (4, 'Purchased AAC audio file'),
    (5, 'AAC audio file');